### ISSUE TITLE
模板匹配的疑问

### ISSUE THREAD

**Issue by zerocdjz** [tangsanli5201/DeepPCB#3]
hi,我觉得模板匹配的方式还是很好的思路，毕竟pcb有很多的类型，若直接用dl的方式来检测，每种类型的pcb都需要样本，所以模板匹配的方式我觉得可以解决样本的问题，但是不知道在推理阶段给定的一张测试图片又是如何从模板库种去寻找与它对应的模板呢？希望能得到解答，谢谢！

**Comment by tangsanli5201** [comment]
首先，基于模板的方法应用的前提是大批量的（例如10张以上）的同一PCB板的印刷。在这种情形下，需要人工对一张PCB板材图像的缺陷区域做修复形成模板图。然后以该模板图对该批量其余图片做相应测试。
